version: '3'
services:
  ardent:
    image: ardent
    ports:
      - "443:443"
    networks:
      - ardent
      - lavaplayer1
  lavaplayer1:
    image: adamratzman/lavaplayer-node
  lavaplayer2:
    image: adamratzman/lavaplayer-node

networks:
  ardent:
    external: true