version: '3'
services:
  ardent:
    image: ardent
    ports:
      - "443:443"
    networks:
      - ardent
  lavaplayer1:
    image: adamratzman/lavaplayer-node
    networks:
      - ardent
  lavaplayer2:
    image: adamratzman/lavaplayer-node
    networks:
      - ardent

networks:
  ardent:
    external: true